/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: modules/ddsc/builtin/BuiltInRaw.c
  Source: /work/vlink/modules/ddsc/builtin/BuiltInRaw.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
// NOLINTBEGIN

#include "BuiltInRaw.h"

static const uint32_t vlink_dds__BuiltInRaw__ops[] = {
    /* BuiltInRaw_ */
    DDS_OP_ADR | DDS_OP_TYPE_8BY, offsetof(vlink_dds__BuiltInRaw_, id),
    DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof(vlink_dds__BuiltInRaw_, data), DDS_OP_RTS};

const dds_topic_descriptor_t vlink_dds__BuiltInRaw__desc = {.m_size = sizeof(vlink_dds__BuiltInRaw_),
                                                            .m_align = dds_alignof(vlink_dds__BuiltInRaw_),
                                                            .m_flagset = 0u,
                                                            .m_nkeys = 0u,
                                                            .m_typename = "vlink::dds_::BuiltInRaw_",
                                                            .m_keys = NULL,
                                                            .m_nops = 3,
                                                            .m_ops = vlink_dds__BuiltInRaw__ops,
                                                            .m_meta = ""};

// NOLINTEND
