/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: modules/ddsc/builtin/BuiltInRaw.h
  Source: /work/vlink/modules/ddsc/builtin/BuiltInRaw.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
// NOLINTBEGIN

#ifndef DDSC_MODULES_DDSC_BUILTIN_BUILTINRAW_H
#define DDSC_MODULES_DDSC_BUILTIN_BUILTINRAW_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet {
  uint32_t _maximum;
  uint32_t _length;
  uint8_t* _buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() ((dds_sequence_octet*)dds_alloc(sizeof(dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) ((uint8_t*)dds_alloc((l) * sizeof(uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct vlink_dds__BuiltInRaw_ {
  uint64_t id;
  dds_sequence_octet data;
} vlink_dds__BuiltInRaw_;

extern const dds_topic_descriptor_t vlink_dds__BuiltInRaw__desc;

#define vlink_dds__BuiltInRaw___alloc() ((vlink_dds__BuiltInRaw_*)dds_alloc(sizeof(vlink_dds__BuiltInRaw_)));

#define vlink_dds__BuiltInRaw__free(d, o) dds_sample_free((d), &vlink_dds__BuiltInRaw__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_MODULES_DDSC_BUILTIN_BUILTINRAW_H */

// NOLINTEND
