// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BuiltInRaw.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

// NOLINTBEGIN

#ifndef FAST_DDS_GENERATED__VLINK_BUILTINRAW_HPP
#define FAST_DDS_GENERATED__VLINK_BUILTINRAW_HPP

#include <cstdint>
#include <utility>
#include <vector>

#include "./base/bytes.h"

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec(dllexport)
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BUILTINRAW_SOURCE)
#define BUILTINRAW_DllAPI __declspec(dllexport)
#else
#define BUILTINRAW_DllAPI __declspec(dllimport)
#endif  // BUILTINRAW_SOURCE
#else
#define BUILTINRAW_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define BUILTINRAW_DllAPI
#endif  // _WIN32

namespace vlink {

/*!
 * @brief This class represents the structure BuiltInRaw defined by the user in the IDL file.
 * @ingroup BuiltInRaw
 */
class BuiltInRaw {
 public:
  /*!
   * @brief Default constructor.
   */
  eProsima_user_DllExport BuiltInRaw() {}

  /*!
   * @brief Default destructor.
   */
  eProsima_user_DllExport ~BuiltInRaw() {}

  /*!
   * @brief Copy constructor.
   * @param x Reference to the object BuiltInRaw that will be copied.
   */
  eProsima_user_DllExport BuiltInRaw(const BuiltInRaw& x) {
    m_id = x.m_id;

    m_data = x.m_data;
  }

  /*!
   * @brief Move constructor.
   * @param x Reference to the object BuiltInRaw that will be copied.
   */
  eProsima_user_DllExport BuiltInRaw(BuiltInRaw&& x) noexcept {
    m_id = x.m_id;
    m_data = std::move(x.m_data);
  }

  /*!
   * @brief Copy assignment.
   * @param x Reference to the object BuiltInRaw that will be copied.
   */
  eProsima_user_DllExport BuiltInRaw& operator=(const BuiltInRaw& x) {
    m_id = x.m_id;

    m_data = x.m_data;

    return *this;
  }

  /*!
   * @brief Move assignment.
   * @param x Reference to the object BuiltInRaw that will be copied.
   */
  eProsima_user_DllExport BuiltInRaw& operator=(BuiltInRaw&& x) noexcept {
    m_id = x.m_id;
    m_data = std::move(x.m_data);
    return *this;
  }

  /*!
   * @brief Comparison operator.
   * @param x BuiltInRaw object to compare.
   */
  eProsima_user_DllExport bool operator==(const BuiltInRaw& x) const { return (m_id == x.m_id && m_data == x.m_data); }

  /*!
   * @brief Comparison operator.
   * @param x BuiltInRaw object to compare.
   */
  eProsima_user_DllExport bool operator!=(const BuiltInRaw& x) const { return !(*this == x); }

  /*!
   * @brief This function sets a value in member id
   * @param _id New value for member id
   */
  eProsima_user_DllExport void id(uint64_t _id) { m_id = _id; }

  /*!
   * @brief This function returns the value of member id
   * @return Value of member id
   */
  eProsima_user_DllExport uint64_t id() const { return m_id; }

  /*!
   * @brief This function returns a reference to member id
   * @return Reference to member id
   */
  eProsima_user_DllExport uint64_t& id() { return m_id; }

  /*!
   * @brief This function copies the value in member data
   * @param _data New value to be copied in member data
   */
  eProsima_user_DllExport void data(const Bytes& _data) { m_data = _data; }

  /*!
   * @brief This function moves the value in member data
   * @param _data New value to be moved in member data
   */
  eProsima_user_DllExport void data(Bytes&& _data) { m_data = std::move(_data); }

  /*!
   * @brief This function returns a constant reference to member data
   * @return Constant reference to member data
   */
  eProsima_user_DllExport const Bytes& data() const { return m_data; }

  /*!
   * @brief This function returns a reference to member data
   * @return Reference to member data
   */
  eProsima_user_DllExport Bytes& data() { return m_data; }

 private:
  uint64_t m_id{0};
  Bytes m_data;
};

}  // namespace vlink

#endif  // _FAST_DDS_GENERATED_VLINK_BUILTINRAW_HPP_

// NOLINTEND
