// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BuiltInRawTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL
 * file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

// NOLINTBEGIN

#include "BuiltInRawTypeObjectSupport.hpp"

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include <mutex>
#include <string>

#include "BuiltInRaw.hpp"

using namespace eprosima::fastdds::dds::xtypes;

namespace vlink {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_BuiltInRaw_type_identifier(TypeIdentifierPair& type_ids_BuiltInRaw) {
  ReturnCode_t return_code_BuiltInRaw{eprosima::fastdds::dds::RETCODE_OK};
  return_code_BuiltInRaw =
      eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
          "vlink::dds_::BuiltInRaw_", type_ids_BuiltInRaw);
  if (eprosima::fastdds::dds::RETCODE_OK != return_code_BuiltInRaw) {
    StructTypeFlag struct_flags_BuiltInRaw = TypeObjectUtils::build_struct_type_flag(
        eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE, false, false);
    QualifiedTypeName type_name_BuiltInRaw = "vlink::dds_::BuiltInRaw_";
    eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_BuiltInRaw;
    eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_BuiltInRaw;
    CompleteTypeDetail detail_BuiltInRaw = TypeObjectUtils::build_complete_type_detail(
        type_ann_builtin_BuiltInRaw, ann_custom_BuiltInRaw, type_name_BuiltInRaw.to_string());
    CompleteStructHeader header_BuiltInRaw;
    header_BuiltInRaw = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_BuiltInRaw);
    CompleteStructMemberSeq member_seq_BuiltInRaw;
    {
      TypeIdentifierPair type_ids_id;
      ReturnCode_t return_code_id{eprosima::fastdds::dds::RETCODE_OK};
      return_code_id =
          eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
              "_uint64_t", type_ids_id);

      if (eprosima::fastdds::dds::RETCODE_OK != return_code_id) {
        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                           "id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
        return;
      }
      StructMemberFlag member_flags_id = TypeObjectUtils::build_struct_member_flag(
          eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false);
      MemberId member_id_id = 0x00000000;
      bool common_id_ec{false};
      CommonStructMember common_id{TypeObjectUtils::build_common_struct_member(
          member_id_id, member_flags_id,
          TypeObjectUtils::retrieve_complete_type_identifier(type_ids_id, common_id_ec))};
      if (!common_id_ec) {
        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure id member TypeIdentifier inconsistent.");
        return;
      }
      MemberName name_id = "id";
      eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_id;
      ann_custom_BuiltInRaw.reset();
      CompleteMemberDetail detail_id =
          TypeObjectUtils::build_complete_member_detail(name_id, member_ann_builtin_id, ann_custom_BuiltInRaw);
      CompleteStructMember member_id = TypeObjectUtils::build_complete_struct_member(common_id, detail_id);
      TypeObjectUtils::add_complete_struct_member(member_seq_BuiltInRaw, member_id);
    }
    {
      TypeIdentifierPair type_ids_data;
      ReturnCode_t return_code_data{eprosima::fastdds::dds::RETCODE_OK};
      return_code_data =
          eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
              "anonymous_sequence_byte_unbounded", type_ids_data);

      if (eprosima::fastdds::dds::RETCODE_OK != return_code_data) {
        return_code_data = eprosima::fastdds::dds::DomainParticipantFactory::get_instance()
                               ->type_object_registry()
                               .get_type_identifiers("_byte", type_ids_data);

        if (eprosima::fastdds::dds::RETCODE_OK != return_code_data) {
          EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                             "Sequence element TypeIdentifier unknown to TypeObjectRegistry.");
          return;
        }
        bool element_identifier_anonymous_sequence_byte_unbounded_ec{false};
        TypeIdentifier* element_identifier_anonymous_sequence_byte_unbounded{
            new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(
                type_ids_data, element_identifier_anonymous_sequence_byte_unbounded_ec))};
        if (!element_identifier_anonymous_sequence_byte_unbounded_ec) {
          EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
          return;
        }
        EquivalenceKind equiv_kind_anonymous_sequence_byte_unbounded = EK_COMPLETE;
        if (TK_NONE == type_ids_data.type_identifier2()._d()) {
          equiv_kind_anonymous_sequence_byte_unbounded = EK_BOTH;
        }
        CollectionElementFlag element_flags_anonymous_sequence_byte_unbounded = 0;
        PlainCollectionHeader header_anonymous_sequence_byte_unbounded = TypeObjectUtils::build_plain_collection_header(
            equiv_kind_anonymous_sequence_byte_unbounded, element_flags_anonymous_sequence_byte_unbounded);
        {
          SBound bound = 0;
          PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(
              header_anonymous_sequence_byte_unbounded, bound,
              eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_byte_unbounded));
          if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
              TypeObjectUtils::build_and_register_s_sequence_type_identifier(
                  seq_sdefn, "anonymous_sequence_byte_unbounded", type_ids_data)) {
            EPROSIMA_LOG_ERROR(
                XTYPES_TYPE_REPRESENTATION,
                "anonymous_sequence_byte_unbounded already registered in TypeObjectRegistry for a different type.");
          }
        }
      }
      StructMemberFlag member_flags_data = TypeObjectUtils::build_struct_member_flag(
          eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD, false, false, false, false);
      MemberId member_id_data = 0x00000001;
      bool common_data_ec{false};
      CommonStructMember common_data{TypeObjectUtils::build_common_struct_member(
          member_id_data, member_flags_data,
          TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, common_data_ec))};
      if (!common_data_ec) {
        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data member TypeIdentifier inconsistent.");
        return;
      }
      MemberName name_data = "data";
      eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data;
      ann_custom_BuiltInRaw.reset();
      CompleteMemberDetail detail_data =
          TypeObjectUtils::build_complete_member_detail(name_data, member_ann_builtin_data, ann_custom_BuiltInRaw);
      CompleteStructMember member_data = TypeObjectUtils::build_complete_struct_member(common_data, detail_data);
      TypeObjectUtils::add_complete_struct_member(member_seq_BuiltInRaw, member_data);
    }
    CompleteStructType struct_type_BuiltInRaw =
        TypeObjectUtils::build_complete_struct_type(struct_flags_BuiltInRaw, header_BuiltInRaw, member_seq_BuiltInRaw);
    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
        TypeObjectUtils::build_and_register_struct_type_object(struct_type_BuiltInRaw, type_name_BuiltInRaw.to_string(),
                                                               type_ids_BuiltInRaw)) {
      EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                         "vlink::BuiltInRaw already registered in TypeObjectRegistry for a different type.");
    }
  }
}

}  // namespace vlink

// NOLINTEND
