// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file BuiltInRaw.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

// NOLINTBEGIN

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
[[maybe_unused]] char dummy;
}  // namespace
#endif  // _WIN32

#include "BuiltInRaw.hpp"

#include <fastcdr/Cdr.h>
#include <fastcdr/exceptions/BadParamException.h>

#define VLINK_ENABLE_DDS_HACK

#ifdef VLINK_ENABLE_DDS_HACK
#include "../thirdparty/access_private.h"

#if FASTCDR_VERSION_MAJOR >= 2
ACCESS_PRIVATE_FIELD(eprosima::fastcdr::Cdr, eprosima::fastcdr::FastBuffer::iterator, offset_)
ACCESS_PRIVATE_FIELD(eprosima::fastcdr::Cdr, eprosima::fastcdr::FastBuffer::iterator, end_)
#else
ACCESS_PRIVATE_FIELD(eprosima::fastcdr::Cdr, eprosima::fastcdr::FastBuffer::iterator, m_currentPosition)
ACCESS_PRIVATE_FIELD(eprosima::fastcdr::Cdr, eprosima::fastcdr::FastBuffer::iterator, m_lastPosition)
#endif

#endif

using namespace eprosima::fastcdr::exception;

#include <utility>

#define vlink_BuiltInRaw_max_cdr_typesize 112ULL;
#define vlink_BuiltInRaw_max_key_cdr_typesize 0ULL;

namespace vlink {

BuiltInRaw::BuiltInRaw() {
  // unsigned long long m_id
  m_id = 0;
  // sequence<octet> m_data
}

BuiltInRaw::~BuiltInRaw() {}

BuiltInRaw::BuiltInRaw(const BuiltInRaw& x) {
  m_id = x.m_id;
  m_data = x.m_data;
}

BuiltInRaw::BuiltInRaw(BuiltInRaw&& x) noexcept {
  m_id = x.m_id;
  m_data = std::move(x.m_data);
}

BuiltInRaw& BuiltInRaw::operator=(const BuiltInRaw& x) {
  m_id = x.m_id;
  m_data = x.m_data;

  return *this;
}

BuiltInRaw& BuiltInRaw::operator=(BuiltInRaw&& x) noexcept {
  m_id = x.m_id;
  m_data = std::move(x.m_data);

  return *this;
}

bool BuiltInRaw::operator==(const BuiltInRaw& x) const { return (m_id == x.m_id && m_data == x.m_data); }

bool BuiltInRaw::operator!=(const BuiltInRaw& x) const { return !(*this == x); }

size_t BuiltInRaw::getMaxCdrSerializedSize(size_t current_alignment) {
  static_cast<void>(current_alignment);
  return vlink_BuiltInRaw_max_cdr_typesize;
}

size_t BuiltInRaw::getCdrSerializedSize(const BuiltInRaw& data, size_t current_alignment) {
  (void)data;
  size_t initial_alignment = current_alignment;

  current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);

  current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

  if (data.data().size() > 0) {
    current_alignment += (data.data().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
  }

  return current_alignment - initial_alignment;
}

void BuiltInRaw::serialize(eprosima::fastcdr::Cdr& scdr) const {
  scdr << m_id;
  scdr << static_cast<uint32_t>(m_data.size());

#if FASTCDR_VERSION_MAJOR >= 2
  scdr.serialize_array(m_data.data(), m_data.size());
#else
  scdr.serializeArray(m_data.data(), m_data.size());
#endif
}

void BuiltInRaw::deserialize(eprosima::fastcdr::Cdr& dcdr) {
  dcdr >> m_id;

  uint32_t length = 0;
  dcdr >> length;

  if (length == 0) {
    m_data.clear();
    return;
  }

#ifdef VLINK_ENABLE_DDS_HACK
#if FASTCDR_VERSION_MAJOR >= 2
  auto& offset = access_private::offset_(dcdr);
  auto& end = access_private::end_(dcdr);

  if (length > end - offset) {
    return;
  }

  m_data = Bytes::shallow_copy(reinterpret_cast<uint8_t*>(dcdr.get_current_position()), length);
#else
  auto& current_position = access_private::m_currentPosition(dcdr);
  auto& last_position = access_private::m_lastPosition(dcdr);

  if (length > last_position - current_position) {
    return;
  }

  m_data = Bytes::shallow_copy(reinterpret_cast<uint8_t*>(dcdr.getCurrentPosition()), length);
#endif

#else

  m_data = Bytes::create(length);

#if FASTCDR_VERSION_MAJOR >= 2
  dcdr.deserialize_array(m_data.data(), m_data.size());
#else
  dcdr.deserializeArray(m_data.data(), m_data.size());
#endif

#endif
}

/*!
 * @brief This function sets a value in member id
 * @param _id New value for member id
 */
void BuiltInRaw::id(uint64_t _id) { m_id = _id; }

/*!
 * @brief This function returns the value of member id
 * @return Value of member id
 */
uint64_t BuiltInRaw::id() const { return m_id; }

/*!
 * @brief This function returns a reference to member id
 * @return Reference to member id
 */
uint64_t& BuiltInRaw::id() { return m_id; }

/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void BuiltInRaw::data(const Bytes& _data) { m_data = _data; }

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void BuiltInRaw::data(Bytes&& _data) { m_data = std::move(_data); }

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const Bytes& BuiltInRaw::data() const { return m_data; }

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
Bytes& BuiltInRaw::data() { return m_data; }

size_t BuiltInRaw::getKeyMaxCdrSerializedSize(size_t current_alignment) {
  static_cast<void>(current_alignment);
  return vlink_BuiltInRaw_max_key_cdr_typesize;
}

bool BuiltInRaw::isKeyDefined() { return false; }

void BuiltInRaw::serializeKey(eprosima::fastcdr::Cdr& scdr) const { (void)scdr; }

}  // namespace vlink

// NOLINTEND
