FROM fedora:43

RUN dnf install -y \
      cmake \
      ccache \
      file \
      gcc-c++ \
      git \
      glibc-static \
      libacl-devel \
      libstdc++-static \
      libzstd-devel \
      make \
      openssl-devel \
      patch \
      pkgconf-pkg-config \
      rpm-build \
      sqlite-devel \
      tar \
      zstd \
    && dnf clean all
