FROM fedora:43

RUN dnf install -y \
      cmake \
      ccache \
      gcc-c++ \
      git \
      libacl-devel \
      libzstd-devel \
      make \
      openssl-devel \
      patch \
      pkgconf-pkg-config \
      rpm-build \
      sqlite-devel \
      tar \
      zstd \
    && dnf clean all
