# NDK
if(NOT DEFINED ENV{ANDROID_NDK})
  message(FATAL_ERROR "You need to set the ANDROID_NDK environment.")
endif()
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_ANDROID_NDK $ENV{ANDROID_NDK})
set(CMAKE_ANDROID_STL_TYPE c++_shared)

# Root
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
if(DEFINED ENV{ANDROID_INSTALL_PREFIX})
  set(ANDROID_INSTALL_PREFIX "$ENV{ANDROID_INSTALL_PREFIX}")
  list(PREPEND CMAKE_FIND_ROOT_PATH "${ANDROID_INSTALL_PREFIX}")
  list(PREPEND _pkg_config "${ANDROID_INSTALL_PREFIX}/lib/pkgconfig")
  set(CMAKE_INSTALL_PREFIX
      "${ANDROID_INSTALL_PREFIX}"
      CACHE PATH "Install path"
  )
  set(CMAKE_C_FLAGS "-I${ANDROID_INSTALL_PREFIX}/include -L${ANDROID_INSTALL_PREFIX}/lib ${CMAKE_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "-I${ANDROID_INSTALL_PREFIX}/include -L${ANDROID_INSTALL_PREFIX}/lib ${CMAKE_CXX_FLAGS}")
  list(FIND CMAKE_FIND_ROOT_PATH "${CMAKE_INSTALL_PREFIX}" _find_index)
  if(_find_index EQUAL -1 AND NOT "${CMAKE_INSTALL_PREFIX}" STREQUAL "${ANDROID_INSTALL_PREFIX}")
    list(PREPEND CMAKE_FIND_ROOT_PATH "${CMAKE_INSTALL_PREFIX}")
    list(PREPEND _pkg_config "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig")
  endif()
endif()
set(ENV{PKG_CONFIG_PATH} "${_pkg_config}")
unset(_find_index)
unset(_pkg_config)

# Flags
if(DEFINED ENV{CFLAGS})
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} $ENV{CFLAGS}")
endif()

if(DEFINED ENV{CXXFLAGS})
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} $ENV{CXXFLAGS}")
endif()
