if(DEFINED ENV{OE_CMAKE_TOOLCHAIN_FILE})
  include($ENV{OE_CMAKE_TOOLCHAIN_FILE})
endif()

set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

include(${CMAKE_CURRENT_LIST_DIR}/linux.toolchain.common.cmake)
