/*
 * Copyright (C) 2026 by Thun Lu. All rights reserved.
 * Author: Thun Lu <thun.lu@zohomail.cn>
 * Repo:   https://github.com/thun-res/vlink
 *  _    __   __      _           __
 * | |  / /  / /     (_) ____    / /__
 * | | / /  / /     / / / __ \  / //_/
 * | |/ /  / /___  / / / / / / / ,<
 * |___/  /_____/ /_/ /_/ /_/ /_/|_|
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @file intra_data.h
 * @brief Reference-counted in-process payload type used by the @c intra:// backend.
 *
 * @details
 * This is an internal implementation header used by the public publisher and
 * subscriber templates when they target the @c intra:// transport; it should not
 * be included directly by application code.  @c IntraData is the shared-ownership
 * vehicle that lets a co-located publisher and subscriber exchange a message by
 * pointer instead of going through a full serialise / deserialise round trip.
 *
 * @par In-process hand-off
 * @code
 *      Publisher thread                                  Subscriber thread
 *      ----------------                                  ------------------
 *      data = MyMsgIntra::create()         shared_ptr -> queue
 *      data->value = ...                       ^
 *      pub.publish(data)  ---------------------+
 *                                              v
 *                                           sub.listen()
 *                                              |
 *                                              v
 *                                       use data->value directly
 * @endcode
 *
 * @par IntraDataType contract
 * Concrete subtypes emitted by @c VLINK_INTRA_DATA_DECLARE add:
 * - A typed @c value member carrying the user payload.
 * - @c operator<< and @c operator>> for on-demand serialisation when the
 *   message has to be replicated across a non-intra boundary (e.g. recording).
 * - @c get_serialized_size(), @c get_serialized_type() and @c get_schema_type()
 *   helpers shared with the public @c Serializer API.
 *
 * @par Example
 * @code
 * // 1. Declare the generated container pair next to the message type:
 * VLINK_INTRA_DATA_DECLARE(MyProtoMsg, MyProtoIntra)
 *
 * // 2. Publish (zero-copy path):
 * auto data = MyProtoIntra::create();
 * data->value.set_field(42);
 * pub.publish(data);
 *
 * // 3. Subscribe (zero-copy path):
 * sub.listen([](const MyProtoIntra& intra) {
 *   process(intra->value);
 * });
 * @endcode
 *
 * @note Only the @c intra:// transport understands @c IntraData; calling
 *       @c write(IntraData) on any other publisher backend logs a warning and
 *       returns @c false.
 */

#pragma once

#include <memory>
#include <string>

#include "../serializer.h"
#include "./types.h"

namespace vlink {

/**
 * @struct IntraDataType
 * @brief Polymorphic base of every in-process payload container.
 *
 * @details
 * Concrete subtypes are emitted by @c VLINK_INTRA_DATA_DECLARE.  They store
 * the actual message value and implement the serialisation operators that
 * convert between the in-memory representation and a @c Bytes buffer when the
 * message crosses a transport boundary.
 */
struct IntraDataType {
  IntraDataType() = default;
  virtual ~IntraDataType() = default;
};

/**
 * @brief Shared-ownership handle for an @c IntraDataType payload.
 *
 * @details
 * Publishers and subscribers exchange messages by copying this @c shared_ptr,
 * avoiding any payload copy.  Use the @c declare_name wrapper generated by
 * @c VLINK_INTRA_DATA_DECLARE, or downcast manually with
 * @c std::static_pointer_cast.
 */
using IntraData = std::shared_ptr<IntraDataType>;

}  // namespace vlink

/**
 * @def VLINK_INTRA_DATA_DECLARE
 * @brief Emits a typed in-process container pair around an arbitrary message type.
 *
 * @details
 * Expansion produces:
 *
 * -# @c declare_name##Type -- a concrete @c IntraDataType subclass with:
 *    - @c target_type value member.
 *    - @c static constexpr kValueType matching @c Serializer::get_type_of<>.
 *    - @c operator<<(const Bytes&) deserialising into @c value.
 *    - @c operator>>(Bytes&) serialising from @c value.
 *    - @c get_serialized_size(), @c get_serialized_type() and
 *      @c get_schema_type() helpers consistent with the public serializer API.
 *    - A @c static_assert ensuring @c target_type is a supported serializer type.
 *
 * -# @c declare_name -- a @c std::shared_ptr<declare_name##Type> wrapper with
 *    constructors that accept the underlying @c shared_ptr and a static
 *    @c create() factory that allocates a fresh instance.
 *
 * The static @c get_serialized_type() returns an empty string for raw @c Bytes
 * instantiations by design; this matches the contract documented in
 * @c serializer.h.
 *
 * @param target_type   User message type, must satisfy @c Serializer::is_supported.
 * @param declare_name  Identifier prefix for the generated container types.
 */
#define VLINK_INTRA_DATA_DECLARE(target_type, declare_name)                                              \
  struct declare_name##Type : public vlink::IntraDataType {                                              \
    target_type value;                                                                                   \
                                                                                                         \
    static constexpr vlink::Serializer::Type kValueType = vlink::Serializer::get_type_of<target_type>(); \
                                                                                                         \
    static_assert(vlink::Serializer::is_supported(kValueType),                                           \
                  "VLINK_INTRA_DATA_DECLARE(target_type) is not a supported Serializer type.");          \
                                                                                                         \
    bool operator<<(const vlink::Bytes& bytes) noexcept {                                                \
      return vlink::Serializer::deserialize<kValueType>(bytes, value);                                   \
    }                                                                                                    \
                                                                                                         \
    bool operator>>(vlink::Bytes& bytes) const noexcept {                                                \
      return vlink::Serializer::serialize<kValueType>(value, bytes);                                     \
    }                                                                                                    \
                                                                                                         \
    [[nodiscard]] size_t get_serialized_size() const noexcept {                                          \
      return vlink::Serializer::get_serialized_size<kValueType>(value);                                  \
    }                                                                                                    \
                                                                                                         \
    [[nodiscard]] static std::string get_serialized_type() noexcept {                                    \
      return vlink::Serializer::get_serialized_type<kValueType, target_type>();                          \
    }                                                                                                    \
                                                                                                         \
    [[nodiscard]] static constexpr vlink::SchemaType get_schema_type() noexcept {                        \
      return vlink::Serializer::get_schema_type<kValueType, target_type>();                              \
    }                                                                                                    \
  };                                                                                                     \
                                                                                                         \
  struct declare_name : public std::shared_ptr<declare_name##Type> {                                     \
    using Base = std::shared_ptr<declare_name##Type>;                                                    \
    using Base::Base;                                                                                    \
                                                                                                         \
    /*NOLINTBEGIN*/                                                                                      \
    declare_name() noexcept = default;                                                                   \
                                                                                                         \
    declare_name(Base&& other) noexcept : Base(std::move(other)) {}                                      \
                                                                                                         \
    declare_name(const Base& other) noexcept : Base(other) {}                                            \
                                                                                                         \
    [[nodiscard]] static declare_name create() noexcept {                                                \
      return declare_name(std::make_shared<declare_name##Type>());                                       \
    }                                                                                                    \
    /*NOLINTEND*/                                                                                        \
  };
