# Common
set(CMAKE_SYSTEM_NAME QNX)
set(UNIX YES)
set(QNX YES)
set(CMAKE_PLATFORM_NO_VERSIONED_SONAME YES)

# SDP
if(NOT DEFINED ENV{QNX_HOST})
  message(FATAL_ERROR "Environment variable QNX_HOST not set!")
endif(NOT DEFINED ENV{QNX_HOST})
if(NOT DEFINED ENV{QNX_TARGET})
  message(FATAL_ERROR "Environment variable QNX_TARGET not set!")
endif(NOT DEFINED ENV{QNX_TARGET})

# Compiler
set(QNX_HOST "$ENV{QNX_HOST}")
set(QNX_TARGET "$ENV{QNX_TARGET}")
set(QNX_ARCH "${CMAKE_SYSTEM_PROCESSOR}")
set(QNX_HOSTSUFFIX "${CMAKE_EXECUTABLE_SUFFIX}")
set(CMAKE_C_COMPILER "${QNX_HOST}/usr/bin/qcc${QNX_HOSTSUFFIX}")
set(CMAKE_CXX_COMPILER "${QNX_HOST}/usr/bin/q++${QNX_HOSTSUFFIX}")
set(CMAKE_C_COMPILER_TARGET "gcc_${QNX_OSLIST}${QNX_CPUVAR}")
set(CMAKE_CXX_COMPILER_TARGET "gcc_${QNX_OSLIST}${QNX_CPUVAR}")
set(CMAKE_ASM_COMPILER_TARGET "gcc_${QNX_OSLIST}${QNX_CPUVAR}")
set(CMAKE_AR
    "${QNX_HOST}/usr/bin/${QNX_OSLIST}${QNX_ARCH}-ar${QNX_HOSTSUFFIX}"
    CACHE PATH "QNX ar"
)
set(CMAKE_RANLIB
    "${QNX_HOST}/usr/bin/${QNX_OSLIST}${QNX_ARCH}-ranlib${QNX_HOSTSUFFIX}"
    CACHE PATH "QNX ranlib"
)
set(CMAKE_LINKER
    "${QNX_HOST}/usr/bin/${QNX_OSLIST}${QNX_ARCH}-ld${QNX_HOSTSUFFIX}"
    CACHE PATH "QNX ld"
)
set(CMAKE_NM
    "${QNX_HOST}/usr/bin/${QNX_OSLIST}${QNX_ARCH}-nm${QNX_HOSTSUFFIX}"
    CACHE PATH "QNX nm"
)
set(CMAKE_OBJCOPY
    "${QNX_HOST}/usr/bin/${QNX_OSLIST}${QNX_ARCH}-objcopy${QNX_HOSTSUFFIX}"
    CACHE PATH "QNX objcopy"
)
set(CMAKE_OBJDUMP
    "${QNX_HOST}/usr/bin/${QNX_OSLIST}${QNX_ARCH}-objdump${QNX_HOSTSUFFIX}"
    CACHE PATH "QNX objdump"
)
set(CMAKE_STRIP
    "${QNX_HOST}/usr/bin/${QNX_OSLIST}${QNX_ARCH}-strip${QNX_HOSTSUFFIX}"
    CACHE PATH "QNX strip"
)
mark_as_advanced(
  CMAKE_AR
  CMAKE_RANLIB
  CMAKE_LINKER
  CMAKE_NM
  CMAKE_OBJCOPY
  CMAKE_OBJDUMP
  CMAKE_STRIP
)

# Install
if(DEFINED ENV{QNX_INSTALL_PREFIX})
  set(QNX_INSTALL_PREFIX "$ENV{QNX_INSTALL_PREFIX}")
else()
  set(QNX_INSTALL_PREFIX "${QNX_TARGET}/${QNX_CPUVAR}/usr/local")
endif()
set(CMAKE_INSTALL_PREFIX
    "${QNX_INSTALL_PREFIX}"
    CACHE PATH "Install path"
)

# Root
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
list(PREPEND CMAKE_FIND_ROOT_PATH "${QNX_INSTALL_PREFIX}")
list(PREPEND CMAKE_FIND_ROOT_PATH "${QNX_TARGET}/${QNX_CPUVAR}")
list(PREPEND CMAKE_FIND_ROOT_PATH "${QNX_TARGET}/${QNX_CPUVAR}/usr")
list(PREPEND _pkg_config "${QNX_INSTALL_PREFIX}/lib/pkgconfig")
list(PREPEND _pkg_config "${QNX_TARGET}/${QNX_CPUVAR}/lib/pkgconfig")
list(PREPEND _pkg_config "${QNX_TARGET}/${QNX_CPUVAR}/usr/lib/pkgconfig")
if(DEFINED ENV{INSTALL_ROOT_${QNX_OSLIST}})
  set(QNX_INSTALL_ROOT "$ENV{INSTALL_ROOT_${QNX_OSLIST}}")
endif()
list(FIND CMAKE_FIND_ROOT_PATH "${CMAKE_INSTALL_PREFIX}" _find_index)
if(_find_index EQUAL -1 AND NOT "${CMAKE_INSTALL_PREFIX}" STREQUAL "${QNX_INSTALL_PREFIX}")
  list(PREPEND CMAKE_FIND_ROOT_PATH "${CMAKE_INSTALL_PREFIX}")
  list(PREPEND _pkg_config "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig")
endif()
set(ENV{PKG_CONFIG_PATH} "${_pkg_config}")
unset(_find_index)
unset(_pkg_config)

# Option
set(CMAKE_C_FLAGS "-D_QNX_SOURCE=1 -I${QNX_INSTALL_PREFIX}/include -L${QNX_INSTALL_PREFIX}/lib ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "-D_QNX_SOURCE=1 -I${QNX_INSTALL_PREFIX}/include -L${QNX_INSTALL_PREFIX}/lib ${CMAKE_CXX_FLAGS}")
if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.20")
  set(CMAKE_SYSROOT "${QNX_TARGET}")
endif()
set(CMAKE_SKIP_RPATH
    TRUE
    CACHE BOOL "QNX skip rpath"
)
set(CMAKE_EXE_LINKER_FLAGS
    "-Wl,-rpath-link,${QNX_INSTALL_PREFIX}/lib"
    CACHE STRING "QNX exe link rpath"
)
set(CMAKE_SHARED_LINKER_FLAGS
    "-Wl,-rpath-link,${QNX_INSTALL_PREFIX}/lib"
    CACHE STRING "QNX shared link rpath"
)
mark_as_advanced(CMAKE_SKIP_RPATH CMAKE_EXE_LINKER_FLAGS CMAKE_SHARED_LINKER_FLAGS)

# Flags
if(DEFINED ENV{CFLAGS})
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} $ENV{CFLAGS}")
endif()

if(DEFINED ENV{CXXFLAGS})
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} $ENV{CXXFLAGS}")
endif()
