// Generated by tools/autosar/arxml_to_vlink_someip.py. Do not edit.
// Sources: autosar_r25_11_someip_types.arxml

#pragma once

#include <array>
#include <cstdint>
#include <string>
#include <vector>

#include <vlink/serializer.h>

namespace vlink::autosar {

enum class GearMode : uint8_t {
  kPark = 0,
  kDrive = 1,
  kReverse = 2,
};

struct Position final {
  int32_t x{};
  int32_t y{};

  VLINK_SOMEIP_STRUCT_LENGTH(2U)
  VLINK_SOMEIP_FIELDS(x, y)
};

using ObjectList = std::vector<Position>;

using PayloadBytes = vlink::Bytes;

using SampleWindow = std::array<uint16_t, 4>;

struct VehicleState final {
  uint32_t sequence{};
  bool valid{};
  GearMode mode{};
  float temperature{};
  std::string name{};
  Position position{};
  SampleWindow samples{};
  ObjectList objects{};
  PayloadBytes payload{};
  std::array<std::array<uint16_t, 3>, 2> matrix{};

  VLINK_SOMEIP_ENDIAN_LITTLE
  VLINK_SOMEIP_STRUCT_LENGTH(2U)
  VLINK_SOMEIP_FIELDS(
      sequence,
      valid,
      mode,
      temperature,
      VLINK_SOMEIP_LENGTH(name, 2U),
      position,
      VLINK_SOMEIP_LENGTH(samples, 0U),
      VLINK_SOMEIP_LENGTH(objects, 2U),
      VLINK_SOMEIP_LENGTH(payload, 1U),
      matrix
  )
};

using VehicleStateApplication = VehicleState;

inline VehicleStateApplication make_vehicle_state_event_initial_value() {
  return VehicleState{
    static_cast<uint32_t>(7U),
    true,
    GearMode::kDrive,
    20.5F,
    "parked",
    Position{
      static_cast<int32_t>(-5),
      static_cast<int32_t>(8)
    },
    std::array<uint16_t, 4>{
      static_cast<uint16_t>(10U),
      static_cast<uint16_t>(20U),
      static_cast<uint16_t>(30U),
      static_cast<uint16_t>(40U)
    },
    std::vector<Position>{
      Position{
        static_cast<int32_t>(1),
        static_cast<int32_t>(2)
      },
      Position{
        static_cast<int32_t>(-3),
        static_cast<int32_t>(4)
      }
    },
    []() {
      auto bytes = vlink::Bytes::create(4U);
      if (bytes.size() != 4U) {
        return bytes;
      }
      bytes.data()[0] = static_cast<uint8_t>(222U);
      bytes.data()[1] = static_cast<uint8_t>(173U);
      bytes.data()[2] = static_cast<uint8_t>(190U);
      bytes.data()[3] = static_cast<uint8_t>(239U);
      return bytes;
    }(),
    std::array<std::array<uint16_t, 3>, 2>{
      std::array<uint16_t, 3>{
        static_cast<uint16_t>(1U),
        static_cast<uint16_t>(2U),
        static_cast<uint16_t>(3U)
      },
      std::array<uint16_t, 3>{
        static_cast<uint16_t>(4U),
        static_cast<uint16_t>(5U),
        static_cast<uint16_t>(6U)
      }
    }
  };
}

}  // namespace vlink::autosar
