/*
 * Generated by tools/autosar/arxml_to_vlink_someip.py. Do not edit.
 * Repo: https://github.com/thun-res/vlink
 *
 * Sources: autosar_r25_11_someip_matrix.arxml
 * Prototypes: /Matrix/ServiceInterfaces/MatrixService/SimpleEvent
 * Namespace: vlink::autosar::matrix
 *
 * C++17 data types for VLink SOME/IP serialization; generated structures are
 * auto-detected as vlink::Serializer::kSomeipType and serialize via their
 * members or vlink::SomeipSerializer.
 */

#pragma once

#include <vlink/extension/someip_serializer.h>

namespace vlink::autosar::matrix {

// AUTOSAR type: /Matrix/ImplementationTypes/SimplePayload.
// SOME/IP structure deployment: 1-byte length field; 1-byte alignment; big-endian.
struct SimplePayload final {
  // AUTOSAR source: /Matrix/ImplementationTypes/SimplePayload/sequence.
  uint16_t sequence{};

  // AUTOSAR source: /Matrix/ImplementationTypes/SimplePayload/name.
  // AUTOSAR maximum text size: 4 code points.
  // SOME/IP deployment: 1-byte length field.
  std::string name{};

  // AUTOSAR source: /Matrix/ImplementationTypes/SimplePayload/values.
  // AUTOSAR maximum elements: 4.
  // SOME/IP deployment: 1-byte length field.
  std::vector<uint8_t> values{};

  // AUTOSAR source: /Matrix/ImplementationTypes/SimplePayload/tail.
  uint16_t tail{};

  [[nodiscard]] bool check_available() const noexcept { return values.size() <= 4U; }

  VLINK_SOMEIP_ENDIAN_BIG
  VLINK_SOMEIP_STRUCT_LENGTH(1U)
  VLINK_SOMEIP_FIELDS(sequence, VLINK_SOMEIP_LENGTH_MAX(name, 1U, 4U), VLINK_SOMEIP_LENGTH_MAX(values, 1U, 4U), tail)
};

}  // namespace vlink::autosar::matrix
