/*
 * Generated by tools/autosar/arxml_to_vlink_someip.py. Do not edit.
 * Repo: https://github.com/thun-res/vlink
 *
 * Sources: autosar_r25_11_someip_types.arxml
 * Prototypes: /VLink/ServiceInterfaces/VehicleStateService/VehicleStateEvent
 * Namespace: vlink::autosar
 * Options: --byte-arrays-as-bytes
 *
 * C++17 data types for VLink SOME/IP serialization; generated structures are
 * auto-detected as vlink::Serializer::kSomeipType and serialize via their
 * members or vlink::SomeipSerializer.
 */

#pragma once

#include <vlink/extension/someip_serializer.h>

namespace vlink::autosar {

// AUTOSAR type: /VLink/ImplementationTypes/GearMode.
enum class GearMode : uint8_t {
  kPark = 0,
  kDrive = 1,
  kReverse = 2,
};

// AUTOSAR type: /VLink/ImplementationTypes/Position.
// SOME/IP structure deployment: 2-byte length field; 1-byte alignment; inherits top-level payload endian.
struct Position final {
  // AUTOSAR source: /VLink/ImplementationTypes/Position/x.
  int32_t x{};

  // AUTOSAR source: /VLink/ImplementationTypes/Position/y.
  int32_t y{};

  VLINK_SOMEIP_STRUCT_LENGTH(2U)
  VLINK_SOMEIP_FIELDS(x, y)
};

// AUTOSAR type: /VLink/ImplementationTypes/ObjectList.
using ObjectList = std::vector<Position>;

// AUTOSAR type: /VLink/ImplementationTypes/PayloadBytes.
using PayloadBytes = vlink::Bytes;

// AUTOSAR type: /VLink/ImplementationTypes/SampleWindow.
using SampleWindow = std::array<uint16_t, 4>;

// AUTOSAR type: /VLink/ImplementationTypes/VehicleState.
// SOME/IP structure deployment: 2-byte length field; 1-byte alignment; little-endian.
struct VehicleState final {
  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/sequence.
  uint32_t sequence{};

  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/valid.
  bool valid{};

  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/mode.
  GearMode mode{};

  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/temperature.
  float temperature{};

  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/name.
  // AUTOSAR maximum text size: 7 code points.
  // SOME/IP deployment: 2-byte length field.
  std::string name{};

  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/position.
  Position position{};

  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/samples.
  // SOME/IP deployment: 0-byte length field.
  SampleWindow samples{};

  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/objects.
  // AUTOSAR maximum elements: 2.
  // SOME/IP deployment: 2-byte length field.
  ObjectList objects{};

  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/payload.
  // AUTOSAR maximum elements: 4.
  // SOME/IP deployment: 1-byte length field.
  PayloadBytes payload{};

  // AUTOSAR source: /VLink/ImplementationTypes/VehicleState/matrix.
  std::array<std::array<uint16_t, 3>, 2> matrix{};

  [[nodiscard]] bool check_available() const noexcept { return objects.size() <= 2U && payload.size() <= 4U; }

  VLINK_SOMEIP_ENDIAN_LITTLE
  VLINK_SOMEIP_STRUCT_LENGTH(2U)
  VLINK_SOMEIP_FIELDS(
      sequence,
      valid,
      mode,
      temperature,
      VLINK_SOMEIP_LENGTH_MAX(name, 2U, 7U),
      position,
      VLINK_SOMEIP_LENGTH(samples, 0U),
      VLINK_SOMEIP_LENGTH_MAX(objects, 2U, 2U),
      VLINK_SOMEIP_LENGTH_MAX(payload, 1U, 4U),
      matrix
  )

  // AUTOSAR INIT-VALUE source: /VLink/ServiceInterfaces/VehicleStateService/VehicleStateEvent.
  [[nodiscard]] static VehicleState make_default() {
    return VehicleState{
      static_cast<uint32_t>(7U),
      true,
      GearMode::kDrive,
      20.5F,
      "parked",
      Position{static_cast<int32_t>(-5), static_cast<int32_t>(8)},
      std::array<uint16_t, 4>{
        static_cast<uint16_t>(10U),
        static_cast<uint16_t>(20U),
        static_cast<uint16_t>(30U),
        static_cast<uint16_t>(40U),
      },
      std::vector<Position>{
        Position{static_cast<int32_t>(1), static_cast<int32_t>(2)},
        Position{static_cast<int32_t>(-3), static_cast<int32_t>(4)},
      },
      vlink::Bytes{
        static_cast<uint8_t>(222U),
        static_cast<uint8_t>(173U),
        static_cast<uint8_t>(190U),
        static_cast<uint8_t>(239U),
      },
      std::array<std::array<uint16_t, 3>, 2>{
        std::array<uint16_t, 3>{static_cast<uint16_t>(1U), static_cast<uint16_t>(2U), static_cast<uint16_t>(3U)},
        std::array<uint16_t, 3>{static_cast<uint16_t>(4U), static_cast<uint16_t>(5U), static_cast<uint16_t>(6U)},
      },
    };
  }
};

// AUTOSAR type: /VLink/ApplicationTypes/VehicleStateApplication.
using VehicleStateApplication = VehicleState;

}  // namespace vlink::autosar
