// Generated by tools/autosar/arxml_to_vlink_someip.py. Do not edit.
// Sources: autosar_r25_11_someip_features.arxml

#pragma once

#include <array>
#include <cstdint>
#include <map>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include <vlink/extension/someip_serializer.h>
#include <vlink/serializer.h>

namespace vlink::autosar::features {

// AUTOSAR type: /Features/Text16.
using Text16 = std::u16string;

// AUTOSAR type: /Features/Text8.
using Text8 = std::string;

// AUTOSAR type: /Features/Payload.
// SOME/IP structure deployment: no length field; 1-byte alignment; big-endian.
struct Payload final {
  // AUTOSAR source: /Features/Payload/text8.
  // AUTOSAR fixed wire size: 11 bytes.
  // AUTOSAR maximum text size: 4 code points.
  // SOME/IP deployment: 1-byte length field.
  Text8 text8{};

  // AUTOSAR source: /Features/Payload/text16.
  // AUTOSAR fixed wire size: 10 bytes.
  // AUTOSAR maximum text size: 3 code points.
  // SOME/IP deployment: 1-byte length field; UTF-16BE.
  Text16 text16{};

  VLINK_SOMEIP_FIELDS(
      VLINK_SOMEIP_FIXED_STRING_MAX(text8, 11U, 1U, 4U),
      VLINK_SOMEIP_FIXED_UTF16_BE_MAX(text16, 10U, 1U, 3U)
  )
};

// AUTOSAR type: /Features/TlvPayload.
// SOME/IP structure deployment: 1-byte length field; 1-byte alignment; big-endian.
struct TlvPayload final {
  // AUTOSAR source: /Features/TlvPayload/text8.
  // AUTOSAR fixed wire size: 11 bytes.
  // AUTOSAR maximum text size: 4 code points.
  // SOME/IP deployment: TLV data ID 1, dynamic length; 1-byte length field.
  Text8 text8{};

  // AUTOSAR source: /Features/TlvPayload/text16.
  // AUTOSAR fixed wire size: 10 bytes.
  // AUTOSAR maximum text size: 3 code points.
  // SOME/IP deployment: TLV data ID 2, dynamic length; 1-byte length field; UTF-16BE.
  Text16 text16{};

  VLINK_SOMEIP_STRUCT_LENGTH(1U)
  VLINK_SOMEIP_FIELDS(
      VLINK_SOMEIP_TLV_FIXED_STRING_MAX(1, text8, 11U, 1U, vlink::SomeipSerializer::Endian::kBig, 4U),
      VLINK_SOMEIP_TLV_FIXED_STRING_MAX(2, text16, 10U, 1U, vlink::SomeipSerializer::Endian::kBig, 3U)
  )
};

// AUTOSAR type: /Features/StaticTlvPayload.
// SOME/IP structure deployment: 1-byte length field; 1-byte alignment; big-endian.
struct StaticTlvPayload final {
  // AUTOSAR source: /Features/StaticTlvPayload/text8.
  // AUTOSAR fixed wire size: 11 bytes.
  // AUTOSAR maximum text size: 4 code points.
  // SOME/IP deployment: TLV data ID 1, static length; 1-byte length field.
  Text8 text8{};

  VLINK_SOMEIP_STRUCT_LENGTH(1U)
  VLINK_SOMEIP_FIELDS(
      VLINK_SOMEIP_TLV_STATIC_FIXED_STRING_MAX(1, text8, 11U, 1U, vlink::SomeipSerializer::Endian::kBig, 4U)
  )
};

}  // namespace vlink::autosar::features
