// Generated by tools/autosar/arxml_to_vlink_someip.py. Do not edit.
// Sources: autosar_r25_11_someip_advanced.arxml

#pragma once

#include <array>
#include <cstdint>
#include <map>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include <vlink/extension/someip_serializer.h>
#include <vlink/serializer.h>

namespace vlink::autosar::advanced {

// AUTOSAR type: /Advanced/ImplementationTypes/Choice.
using Choice = std::variant<uint16_t, uint32_t>;

// AUTOSAR type: /Advanced/ImplementationTypes/Lookup.
using Lookup = std::map<uint16_t, uint32_t>;

// AUTOSAR type: /Advanced/ImplementationTypes/AdvancedPayload.
// SOME/IP structure deployment: 2-byte length field; 1-byte alignment; big-endian.
struct AdvancedPayload final {
  // AUTOSAR source: /Advanced/ImplementationTypes/AdvancedPayload/title.
  // AUTOSAR maximum text size: 4 code points.
  // SOME/IP deployment: 2-byte length field; UTF-16BE.
  std::u16string title{};

  // AUTOSAR source: /Advanced/ImplementationTypes/AdvancedPayload/lookup.
  // SOME/IP deployment: 2-byte length field.
  Lookup lookup{};

  // AUTOSAR source: /Advanced/ImplementationTypes/AdvancedPayload/samples.
  // AUTOSAR maximum elements: 2.
  // SOME/IP deployment: 2-byte length field.
  std::vector<uint16_t> samples{};

  // AUTOSAR source: /Advanced/ImplementationTypes/AdvancedPayload/choice.
  // SOME/IP deployment: 2-byte length field; 1-byte union selector.
  Choice choice{};

  [[nodiscard]] bool check_available() const noexcept { return samples.size() <= 2U; }

  VLINK_SOMEIP_STRUCT_LENGTH(2U)
  VLINK_SOMEIP_FIELDS(
      VLINK_SOMEIP_UTF16_MAX(title, 2U, vlink::SomeipSerializer::Endian::kBig, 4U),
      VLINK_SOMEIP_LENGTH(lookup, 2U),
      VLINK_SOMEIP_LENGTH_MAX(samples, 2U, 2U),
      VLINK_SOMEIP_UNION(choice, 2U, 1U)
  )
};

// AUTOSAR type: /Advanced/ImplementationTypes/Cube.
using Cube = std::array<std::array<std::array<uint8_t, 2>, 2>, 2>;

// AUTOSAR type: /Advanced/ImplementationTypes/RecordArray/element.
// SOME/IP structure deployment: 2-byte length field; 1-byte alignment; inherits top-level payload endian.
struct RecordArray_element final {
  // AUTOSAR source: /Advanced/ImplementationTypes/RecordArray/element/value.
  uint8_t value{};

  VLINK_SOMEIP_STRUCT_LENGTH(2U)
  VLINK_SOMEIP_FIELDS(value)
};

// AUTOSAR type: /Advanced/ImplementationTypes/RecordArray.
using RecordArray = std::array<RecordArray_element, 2>;

// AUTOSAR type: /Advanced/ImplementationTypes/TlvPayload.
// SOME/IP structure deployment: 2-byte length field; 1-byte alignment; big-endian.
struct TlvPayload final {
  // AUTOSAR source: /Advanced/ImplementationTypes/TlvPayload/label.
  // AUTOSAR maximum text size: 4 code points.
  // SOME/IP deployment: TLV data ID 1, optional, dynamic length; 2-byte length field.
  std::optional<std::string> label{};

  // AUTOSAR source: /Advanced/ImplementationTypes/TlvPayload/code.
  // SOME/IP deployment: TLV data ID 2, fixed-width wire type; shared 2-byte complex length width.
  uint8_t code{};

  // AUTOSAR source: /Advanced/ImplementationTypes/TlvPayload/lookup.
  // SOME/IP deployment: TLV data ID 3, optional, dynamic length; 2-byte length field.
  std::optional<Lookup> lookup{};

  // AUTOSAR source: /Advanced/ImplementationTypes/TlvPayload/values.
  // SOME/IP deployment: TLV data ID 4, optional, dynamic length; 2-byte length field; 3 array dimensions.
  std::optional<Cube> values{};

  // AUTOSAR source: /Advanced/ImplementationTypes/TlvPayload/records.
  // SOME/IP deployment: TLV data ID 5, optional, dynamic length; 2-byte length field.
  std::optional<RecordArray> records{};

  VLINK_SOMEIP_STRUCT_LENGTH(2U)
  VLINK_SOMEIP_FIELDS(
      VLINK_SOMEIP_TLV_LENGTH_MAX(1, label, 2U, 4U),
      VLINK_SOMEIP_TLV_LENGTH(2, code, 2U),
      VLINK_SOMEIP_TLV_LENGTH(3, lookup, 2U),
      VLINK_SOMEIP_TLV_ARRAY_LENGTH(4, values, 2U, 2U, 2U),
      VLINK_SOMEIP_TLV_LENGTH(5, records, 2U)
  )
};

}  // namespace vlink::autosar::advanced
