if(DEFINED ENV{OE_CMAKE_TOOLCHAIN_FILE})
  include($ENV{OE_CMAKE_TOOLCHAIN_FILE})
endif()

set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_OSX_ARCHITECTURES
    "arm64"
    CACHE STRING "Build architecture" FORCE
)

if("$ENV{VLINK_HOST_PLATFORM}" STREQUAL "darwin-aarch64" OR "$ENV{VLINK_HOST_PLATFORM}" STREQUAL "darwin-arm64")
  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
else()
  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()

include(${CMAKE_CURRENT_LIST_DIR}/darwin.toolchain.common.cmake)
