/*
 * Copyright (C) 2026 by Thun Lu. All rights reserved.
 * Author: Thun Lu <thun.lu@zohomail.cn>
 * Repo:   https://github.com/thun-res/vlink
 *  _    __   __      _           __
 * | |  / /  / /     (_) ____    / /__
 * | | / /  / /     / / / __ \  / //_/
 * | |/ /  / /___  / / / / / / / ,<
 * |___/  /_____/ /_/ /_/ /_/ /_/|_|
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <string>

namespace vlink::bench::report::i18n {

inline std::string render_i18n_script_json_en_us() {
  return R"JSON({
    "report_heading_run": "Benchmark",
    "report_heading_report": "report",

    "skip_to_content": "Skip to content",
    "aria_main": "Report content",

    "headline_subtitle": "End-to-end transport, latency, throughput, and serialization benchmark across the requested scenario matrix.",
    "summary_strip_label": "At a glance",
    "summary_pill_pass": "passing",
    "summary_pill_warn": "warning",
    "summary_pill_fail": "failing",
    "summary_pill_skipped": "skipped",
    "summary_pill_planned": "planned",
    "summary_pill_samples": "samples",



    "footer_generated": "Generated by",
    "footer_format": "Single-file offline HTML report",
    "footer_doc": "Read the methodology in doc/13-cli-tools.md",

    "nav_recommendation": "Recommended Targets",
    "nav_overview": "Run Overview",
    "nav_health": "Transport Health",
    "nav_heatmap": "Latency/Throughput",
    "nav_suite_score": "Category Results",
    "nav_planner_notes": "Run Notes",
    "nav_transport_rollup": "Transport Summary",
    "nav_serialization": "Serialization Overview",
    "nav_charts": "Trend Charts",
    "nav_scenario_tables": "Detail Data",

    "overview_title": "Run Overview",
    "overview_samples": "Samples",
    "overview_planned": "Planned Cases",
    "overview_skipped": "Skipped Cases",
    "overview_cases": "Cases",
    "overview_passing": "Passing",
    "overview_warning": "Warning",
    "overview_failing": "Failing",

    "health_badge_failures": "failures",
    "health_badge_warnings": "warnings",
    "health_badge_ok": "all OK",
    "health_url_coverage_h3": "Tested URL Coverage",
    "health_unstable_h3": "Cases to Review",
    "health_note": "Transport Health tells whether this report is trustworthy before you compare scores. It summarizes failed cases, warnings, URL coverage, and problem cases. Green means no obvious problem; yellow means review loss, skipped, or unstable results; red means inspect the problem-case error first. Small loss is still recorded; this section highlights loss, failures, or skips that may affect the conclusion.",

    "dec_score_combined": "total",
    "dec_score_total_title": "Total score, max 120. Weights: 30% latency + 20% throughput + 10% resource + 10% delivery + 10% send-block + 10% coverage + 10% topology, then multiplied by confidence (high 1.00 / solo·medium 0.99 / unknown·noisy 0.95).",
    "dec_confidence_prefix": "conf",

    "heatmap_title": "Latency by Message Size (P50 / P90 / P99, lower is better)",
    "heatmap_note": "Each cell has three bars: P50 / P90 / P99 (left to right), shorter and greener is better. Numbers on the right follow the same order, in μs. Blank = no data, FAIL = case failed.",
    "heatmap_latency_good": "low latency",
    "heatmap_latency_mid": "medium latency",
    "heatmap_latency_bad": "high latency",
    "heatmap_throughput_title": "Throughput by Message Size (received MB/s, higher is better)",
    "heatmap_throughput_note": "This chart uses throughput tests only. Each row is one test target and each column is a message size. The number is mean received MB/s. Longer greener horizontal bars mean the subscriber actually received more data. Blank or failed cells have no valid result.",
    "heatmap_head_transport": "test target \\ message size",

    "profile_title": "Recommended Targets",
    "profile_note": "Cards are sorted by total score for this run. Each card represents one tested URL or transport configuration. Read total score, latency, throughput, CPU, and confidence first; open a card for URL, run mode, and typical metrics.",
    "profile_fact_url_prefix": "protocol/transport",
    "profile_fact_deployment": "run mode",
    "profile_num_best_p95": "best P95 latency",
    "profile_num_best_send_block": "best send-block P99",
    "profile_num_peak": "peak received throughput",
    "profile_num_avg_cpu": "avg CPU",
    "profile_num_cases": "counted runs",
    "profile_num_cpu_ctx": "publisher + subscriber",
    "profile_num_loss": "loss rate",
    "profile_num_loss_ctx": "aggregate / worst case",
    "profile_top_pick_prefix": "Top recommendation:",
    "profile_top_pick_reason": "It is the strongest result in this run; use latency, throughput, and Transport Health below to confirm details.",

    "layer_inprocess": "in-process",
    "layer_crossprocess": "cross-process",
    "layer_unknown": "unknown",

    "scenario_transport_title": "Transport Detail Table",
    "scenario_serialization_title": "Serialization Detail Table",

    "suite_score_title": "Category Results",
    "executive_title": "Result Highlights",
    "planner_notes_title": "Run Notes",
    "transport_rollup_title": "Transport Summary",
    "transport_rollup_note": "Groups each URL/transport configuration into one row for a quick trend view. A row can include multiple message sizes, rates, or topologies, so use latency/throughput comparisons and trend charts for exact comparisons.",
    "serialization_overview_title": "Serialization Overview",
    "methodology_show": "Show methodology",
    "methodology_hide": "Hide methodology",

    "overview_note": "Repeated runs of the same case are merged; averages only count successful runs. Loss is highlighted in the overview, Transport Health, and Recommended Targets headers once it reaches 5%, so trace jitter does not crowd the main verdict. Expand any recommendation card to see the exact loss rate for that URL regardless of threshold.",

    "metrics_title": "Metric Guide",
    "metrics_note": "Terminology used throughout the report. Skim it once and the recommendation, heatmaps, and category results below all become easier to interpret.",
    "th_metric": "Metric",
    "th_meaning": "Meaning",
    "metric_p95_label": "P50 / P90 / P99 latency (and P99.9 / P99.99 in detail tables)",
    "metric_p95_meaning": "Latency percentiles. The heatmap shows P50 (typical), P90 (slower common case), and P99 (tail) side by side; detail tables and scoring also include P99.9 and P99.99 to surface rare slow messages. Lower numbers are better across the board.",
    "metric_mbps_label": "Received MB/s",
    "metric_mbps_meaning": "How many megabytes per second the subscriber actually received. This is the main throughput number.",
    "metric_loss_label": "Loss ratio",
    "metric_loss_meaning": "Messages that were expected but not received. Small loss can happen in stress tests; the report only highlights loss at 5% or higher, and marks very high loss more strongly.",
    "metric_confidence_label": "Confidence",
    "metric_confidence_meaning": "A quick read on result reliability, based on run success, visible loss, and latency sample drops. Low confidence means review Transport Health and problem cases; final judgment still depends on latency and throughput.",
    "metric_payload_label": "Message size / payload",
    "metric_payload_meaning": "The size and type of each message sent during the test. Larger messages usually stress bandwidth, buffers, and copying more.",
    "metric_topology_label": "Connection topology",
    "metric_topology_meaning": "The publisher/subscriber shape, such as 1:1, 1:n, n:1, or n:n. It shows whether a transport scales when more senders or receivers are involved.",
    "metric_cpu_label": "CPU Efficiency",
    "metric_cpu_meaning": "How much throughput is achieved for the CPU used by publisher and subscriber. It helps break ties, but latency and throughput remain the main decision signals.",

    "th_transport": "Transport",
    "th_mode": "Mode",
    "th_url": "URL",
    "th_modes": "Modes",
    "th_passing": "Passing",
    "th_warning": "Warning",
    "th_failing": "Failing",
    "th_unstable_cases": "Problem Cases",
    "th_total_cases": "Total Cases",
    "th_best_recv_mbps": "Best Received MB/s",
    "th_best_p95_us": "Best P95 (us)",
    "th_suite": "Category",
    "th_winner": "Best Result",
    "th_score": "Score",
    "th_coverage": "Coverage",
    "th_conclusion": "Conclusion",
    "th_input_factors": "What is scored",
    "th_gates": "How to read it",
    "th_interpretation": "Best used for",
    "th_payload": "Payload",
    "th_size": "Size",
    "th_encode_mbps": "Encode MB/s",
    "th_decode_mbps": "Decode MB/s",
    "th_status": "Status",
    "th_config": "Config",
    "th_error": "Error",
    "th_rate": "Rate",
    "th_repeats": "Repeats",
    "th_recv_mbps": "Received MB/s",
    "th_mean_p95": "Mean P95 (us)",
    "th_mean_p999": "Mean P99.9 (us)",
    "th_send_block_p99": "Send-block P99 us",
    "th_loss_pct": "Loss %",
    "th_cpu_pct": "CPU %",
    "th_peak_rss_mb": "Peak RSS MB",

    "chart_zoom_in": "Zoom in",
    "chart_zoom_out": "Zoom out",
    "chart_reset": "Reset view",
    "chart_reset_short": "Reset",
    "chart_hint": "wheel=zoom · drag=pan · dblclick=reset",

    "chart_throughput": "Throughput",
    "chart_rate_sweep": "Rate Sweep",
    "chart_latency": "Latency",
    "chart_loss": "Loss",
    "chart_send_block": "Send-block",
    "chart_title_send_block": "Send-block: publish() P99 blocking time / Payload Size",
    "chart_axis_send_block_p99": "Send-block P99 (us)",
    "chart_first_message": "First Message",
    "chart_resource_cpu": "Resource CPU",
    "chart_resource_rss": "Resource RSS",
    "chart_topology_1n": "Topology 1:n",
    "chart_topology_n1": "Topology n:1",
    "chart_topology_nn": "Topology n:n",
    "chart_serialize": "Serialize",
    "chart_deserialize": "Deserialize",

    "chart_title_throughput": "Throughput: Delivered MB/s vs Payload Size",
    "chart_title_rate_sweep": "Rate Sweep: Delivered MB/s vs Offered Msg/s",
    "chart_title_latency": "Latency: Mean Run P95 us vs Payload Size",
    "chart_title_loss": "Loss: Loss Ratio vs Payload Size",
    "chart_title_first_message": "First Message ms vs Payload Size",
    "chart_title_resource_cpu": "Resource: CPU% vs Payload Size",
    "chart_title_resource_rss": "Resource: Peak RSS MB vs Payload Size",
    "chart_title_topology_1n": "Topology 1:n: Delivered MB/s vs Subscribers",
    "chart_title_topology_n1": "Topology n:1: Delivered MB/s vs Publishers",
    "chart_title_topology_nn": "Topology n:n: Delivered MB/s vs Connection Pairs",
    "chart_title_serialize": "Serialize: Encode MB/s vs Payload Size",
    "chart_title_deserialize": "Deserialize: Decode MB/s vs Payload Size",

    "chart_axis_payload_size": "Payload Size",
    "chart_axis_offered_msgs": "Offered Msg/s",
    "chart_axis_subscribers": "Subscribers",
    "chart_axis_publishers": "Publishers",
    "chart_axis_endpoint_pairs": "Connection Pairs",
    "chart_axis_delivered_mbps": "Received MB/s",
)JSON"
         R"JSON(    "chart_axis_p95_latency": "Mean Run P95 Latency (us)",
    "chart_axis_loss_pct": "Loss (%)",
    "chart_axis_first_message": "First Message (ms)",
    "chart_axis_cpu_pct": "CPU (%)",
    "chart_axis_peak_rss": "Peak RSS MB",
    "chart_axis_encode_mbps": "Encode MB/s",
    "chart_axis_decode_mbps": "Decode MB/s",

    "aria_sections": "Sections",
    "aria_chart_controls": "Chart controls",
    "aria_series_legend": "Series legend",
    "aria_language": "Language",

    "meta_version_label": "version",
    "meta_created_label": "created",


    "suite_score_methodology_note_1": "This table scores throughput, latency, backpressure, topology, and serialization separately. Compare scores inside the same category; a latency score and a throughput score are not interchangeable.",
    "suite_score_three_layers_prefix": "Each score is mainly driven by the most important metric for that category, with a small health check for failures, visible loss, latency sample drops, and repeat success.",

    "suite_score_factors_throughput": "Mainly received MB/s, with small checks for send/receive efficiency and health.",
    "suite_score_gates_throughput": "Throughput tests mainly answer how much data was actually received. Health only highlights clear problems.",
    "suite_score_interp_throughput": "Useful for choosing the configuration that carries more data under larger payloads or heavier send pressure.",
    "suite_score_factors_latency": "Mainly tail latency such as P99, with small checks for max latency, jitter, throughput, and health. Larger-payload cases carry higher weight when aggregating across cases.",
    "suite_score_gates_latency": "Latency tests mainly use percentiles. The heatmap visualises P50 (typical) / P90 (slower common case) / P99 (tail), and scoring also weights P99.9 / P99.99 to penalize rare stalls. Lower numbers are better.",
    "suite_score_interp_latency": "Useful for checking whether messages respond quickly and whether slow-message latency stays controlled. Averages can look good while P99 or P99.9 still reveals user-visible stalls.",
    "suite_score_factors_backpressure": "Mainly publisher-side P99 send-block time, with checks for delivered throughput, send/receive efficiency, and health.",
    "suite_score_gates_backpressure": "Backpressure tests simulate slow consumers. Lower publish() blocking time is better, but the run still needs to deliver messages reliably.",
    "suite_score_interp_backpressure": "Useful for spotting transports that stall publisher threads when subscribers fall behind.",
    "suite_score_factors_topology": "Mainly total received MB/s and scaling efficiency, with small checks for send/receive efficiency and health.",
    "suite_score_gates_topology": "Topology tests mainly check whether total throughput keeps up as publishers or subscribers increase.",
    "suite_score_interp_topology": "Useful for one-to-many, many-to-one, and many-to-many deployment shapes.",
    "suite_score_factors_serialization": "Mainly encode/decode speed, also checking coverage, repeat success, efficiency, balance, CPU, and memory.",
    "suite_score_gates_serialization": "Serialization mainly compares encode/decode speed and checks repeat stability.",
    "suite_score_interp_serialization": "Useful for judging data-format cost. It does not represent the full communication path.",

    "executive_highlights_note": "This section highlights the easiest results to notice in this report: highest throughput, lowest latency, topology scaling, and fastest encode/decode. Use it to find leads quickly, then confirm with the recommendation, heatmaps, and problem cases.",
    "insight_highest_1to1_throughput": "Highest 1:1 throughput",
    "insight_lowest_1to1_latency": "Lowest 1:1 latency",
    "insight_highest_1n_throughput": "Highest 1:n total throughput",
    "insight_highest_nn_throughput": "Highest n:n total throughput",
    "insight_fastest_encode": "Fastest encode",
    "insight_url_label": "url",
    "insight_topology_label": "topology",
    "insight_pattern_label": "pattern",
    "insight_recv_label": "received",
    "insight_first_msg_label": "first msg",
    "insight_loss_label": "loss",
    "insight_subscribers_label": "subscribers",
    "insight_publishers_label": "publishers",
    "insight_serialize_label": "serialize",
    "insight_deserialize_label": "deserialize",
    "insight_repeats_label": "repeats",

    "executive_coverage_urls": "url(s),",
    "executive_coverage_transports": "transport(s), and",
    "executive_coverage_modes": "mode(s).",
    "executive_coverage_passing": "normal cases:",
    "executive_coverage_unstable": "problem cases:",
    "executive_coverage_sentence_prefix": "This run covers",
    "executive_broadest_prefix": "The most normal cases come from",
    "executive_broadest_in": "in",
    "executive_broadest_mode_with": "mode with",
    "executive_broadest_suffix": "normal case(s).",
    "executive_broadest_tie_prefix": "All",
    "executive_broadest_tie_middle": "transport(s) share the widest normal coverage with",

    "conclusion_latency_prefix": "Lowest latency:",
    "conclusion_loss_label": "loss",
    "conclusion_topology_prefix": "Best topology scaling:",
    "conclusion_topology_recv": "received",
    "conclusion_topology_scale": "scale efficiency",
    "conclusion_backpressure_prefix": "Lowest publisher blocking:",
    "conclusion_backpressure_send_block": "send-block P99",
    "conclusion_backpressure_recv": "received",
    "conclusion_throughput_prefix": "Best throughput:",
    "conclusion_throughput_recv": "received",
    "conclusion_throughput_first_msg": "first message",
    "conclusion_serialization_prefix": "Best codec slice for",
    "conclusion_serialization_encode": "encode",
    "conclusion_serialization_decode": "decode",

    "coverage_case_suffix": "case(s),",
    "coverage_repeat_success_suffix": "repeat success,",
    "coverage_urls_suffix": "url(s)",
    "coverage_repeat_short": "repeat",

    "transport_rollup_note_long": "Groups results by transport type, run mode, and test category for a quick trend view. Because a row can include multiple message sizes or rates, use latency/throughput comparisons and trend charts for exact comparisons.",
    "serialization_overview_note": "Compares encode and decode speed across payload sizes. Use it to understand serialization cost.",

    "th_mean_recv_mbps": "Mean Received MB/s",
    "th_mean_run_p95_us": "Mean Run P95 us",
    "th_avg_loss_pct": "Loss %",
    "th_mean_peak_rss_mb": "Mean Peak RSS MB",
    "th_mean_encode_mbps": "Mean Encode MB/s",
    "th_mean_decode_mbps": "Mean Decode MB/s",
    "th_mean_encode_cpu_ms": "Mean Encode CPU ms",
    "th_mean_decode_cpu_ms": "Mean Decode CPU ms",
    "th_errors": "Errors",

    "mode_local_direct": "local-direct",
    "mode_local_loop": "local-loop",
    "mode_process": "process",
    "mode_unknown": "unknown",

    "pill_speed_label": "Latency score",
    "pill_capacity_label": "Throughput score",
    "pill_efficiency_label": "Resource score",
    "pill_coverage_label": "Coverage score",
    "pill_speed_title": "Latency sub-score (0-100). Lower tail latency scores higher. Top-level weight 30%.",
    "pill_capacity_title": "Throughput sub-score (0-100). Higher received MB/s scores higher. Top-level weight 20%.",
    "pill_efficiency_title": "Resource (CPU) sub-score (0-100). Higher throughput per CPU scores higher. Top-level weight 10%.",
    "pill_coverage_title": "Coverage sub-score (0-100). Passing cases over total cases attempted; standalone 10% slot in the total.",
    "pill_loss_label": "Loss",
    "pill_loss_title": "Loss ratio",

    "profile_scoring_legend": "Total score is out of 120. Higher is better for the current test mix; weights are 30% latency + 20% throughput + 10% resource + 10% delivery + 10% send-block + 10% coverage + 10% topology, then multiplied by a confidence factor. Sub-pills show: latency / throughput / resource / coverage / delivery / send-block.",
    "pill_delivery_label": "Delivery score",
    "pill_delivery_title": "Delivery sub-score (0-100). Derived from packet loss aggregated across cases; lower loss scores higher. Top-level weight 10%.",
    "pill_send_block_label": "Send-block score",
    "pill_send_block_title": "Send-block sub-score (0-100). Per-case publish() wall-clock duration aggregated to P99; lower blocking time scores higher. Top-level weight 10% — penalizes transports that hold the publisher thread.",

    "profile_formula_title": "Total-score formula (max 120) — each dimension explained",
    "profile_formula_latency": "Latency 30%",
    "profile_formula_latency_desc": "— Subscriber-side end-to-end latency. Per case we weight P95×0.50 + P99×0.35 + P99.9×0.12 + P99.99×0.03 through a payload-aware curve (excellent_us = clamp(80 + payload_KiB·0.40, 80, 1500), poor = excellent×8, log-linear in between). Across cases we use a payload-weighted geometric mean with weight = clamp(1 + 0.27·log1p(payload_KiB), 1, 3) — large payloads weigh 1.5~3× small ones, but the ratio is bounded.",
    "profile_formula_throughput": "Throughput 20%",
    "profile_formula_throughput_desc": "— Subscriber received MB/s. Per case: log1p(recv_mbps)·100 / log1p(1024). Across cases: equal-weight geometric mean within the throughput suite, with topology suite as fallback only when the throughput suite is missing.",
    "profile_formula_resource": "Resource 10%",
    "profile_formula_resource_desc": "— Throughput per CPU. Per case: throughput / (pub_cpu_ms + sub_cpu_ms), normalized 0-100 against the run's best efficiency value. Higher score = more bytes pushed per CPU-millisecond.",
    "profile_formula_delivery": "Delivery 10%",
    "profile_formula_delivery_desc": "— Aggregated loss across all cases: avg_delivery = 100 - loss%. Loss > 5% also lightly cuts per-case latency via a logistic curve (gentle ≤20%, accelerates >20%, capped at ×0.40) to defeat survivor-bias.",
    "profile_formula_send_block": "Send-block 10%",
    "profile_formula_send_block_desc": "— Wall-clock time spent inside publish() per message. Latency and backpressure cases use each case's P99 send-block on a payload-aware curve (excellent = clamp(5 + payload_KiB·0.05, 5, 200) µs, poor = excellent×30). Cases are payload-weighted-geometric-meaned. Penalizes APIs that hold the publisher thread; an async-by-default API will get high marks naturally.",
    "profile_formula_coverage": "Coverage 10%",
    "profile_formula_coverage_desc": "— Passing cases / total cases for this URL. Standalone dimension; also serves as fallback for the topology slot when topology suite is absent.",
    "profile_formula_topology": "Topology 10%",
    "profile_formula_topology_desc": "— Topology suite roll-up (1:n / n:1 / n:n). Falls back to clamp(coverage, 60, 95) when topology suite was not run.",
    "profile_formula_equation": "total = (0.36·latency + 0.24·throughput + 0.12·resource + 0.12·delivery + 0.12·send-block + 0.12·coverage + 0.12·topology) · confidence_factor  (each sub-score is 0-100 → max total 120)",
    "profile_formula_confidence_note": "Confidence is derived from aggregate/worst-case loss% and latency sample drops: <5% high, <15% medium, ≥15% noisy; solo means no peers, unknown means all cases failed. Multipliers: high 1.00 / solo·medium 0.99 / unknown·noisy 0.95.",

    "confidence_high": "high",
    "confidence_medium": "medium",
    "confidence_noisy": "low",
    "confidence_solo": "single target",
    "confidence_unknown": "unknown",

    "suite_score_panel_note": "This table lists the best configuration in each test category. Different categories focus on different signals, so compare scores inside the same category.",

    "status_ok": "OK",
    "status_warn": "WARN",
    "status_fail": "FAIL",
    "status_drop_label": "drop",

    "config_node_label": "node",
    "config_pub_label": "pub",
    "config_sub_label": "sub"
  })JSON";
}

}  // namespace vlink::bench::report::i18n
